### PR TITLE
Separating Dashboard creation into another Notebook

### LINKED ISSUE #35: Dashboard creation to a new notebook
Moving the part of dashboard creation that is currently on notebook 02 to a third notebook.

### PR DESCRIPTION
**Pull request by ignacioct**
Closes #35 

I separated the dashboard creation process into notebook 03 and added our names @davanstrien @davidberenstein1957 for people to send their API KEYs and URLs to us and maintain de multilingual dashboard

### CODE REVIEW

**Review by davidberenstein1957 — COMMENTED** [review]
Looking good, an intiital comment I have is can you remove the `.ipynb_checkpoints`?

**Comment by davidberenstein1957** [comment]
Also, we can make the text for the combined dashboard a bit more engaging and share the language race dashboard URL there too:)

**Comment by ignacioct** [comment]
@davidberenstein1957 thanks for the comments! just uploaded a new version :)

**Comment by davidberenstein1957** [comment]
@ignacioct cool, a final thingy. Could you reference the general dashboard in the readme too?

**Comment by ignacioct** [comment]
> @ignacioct cool, a final thingy. Could you reference the general dashboard in the readme too?

Done! I tried to keep it short, but have to change it if we want more verbosity :)

**Review by davidberenstein1957 — APPROVED** [review]
Awesome @ignacioct

**Comment by ignacioct** [comment]
I think we are ready to merge then @davanstrien 🚀

**Review by davanstrien — APPROVED** [review]
Thanks for working on this :)

**Pull request merged**
