### PR TITLE
Add support for scheduled refresh.

### PR DESCRIPTION
**Pull request by kghamilton89**
Resolves [reported issue](https://discord.com/channels/879548962464493619/1205128865735770142/1221367458989084822).

Changes already live in [Dutch MPEP dashboard Space](https://huggingface.co/spaces/DIBT-Dutch/prompt-translation/commit/2c2ec395b73dedf1059ba6aebdb2bf5e09e11855) and [Russian MPEP dashboard Space](https://huggingface.co/spaces/DIBT-Russian/MPEP_Dashboard/commit/050d51fd8a8fd9a47048ee3e9a91d12bc56a1dfe).

Humble suggestion to add support for automated refresh out of the box.

### CODE REVIEW

**Comment by alvarobartt** [comment]
cc @ignacioct

**Comment by ignacioct** [comment]
Hi @kghamilton89, thanks for the PR. This code looks very similar to the code we initially had to allow background refresh, but it was giving us a lot of problems. The dashboard was getting frozen fairly regularly. Are you not experiencing this? 

If it's working on your side, we could maybe add it as an option or comments in the code, but I and @dvsrepo are skeptics about the `BackgroundScheduler` usage.

**Comment by kghamilton89** [comment]
> Hi @kghamilton89, thanks for the PR. This code looks very similar to the code we initially had to allow background refresh, but it was giving us a lot of problems. The dashboard was getting frozen fairly regularly. Are you not experiencing this?
> 
> If it's working on your side, we could maybe add it as an option or comments in the code, but I and @dvsrepo are skeptics about the `BackgroundScheduler` usage.

In fact yes, sometimes I see that dashboard hangs when I leave it open for a period of time. Example, I open dashboard and leave it open for an arbitrary period of time. I return to dash and see "error" for all visualizations.

Refresh always resolves this issue and looking at console shows `500` server error for Argilla servers.

Do you have any hypothesis for errors? As I say in [here](https://discord.com/channels/879548962464493619/1205128865735770142/1221398680477630494) expecting Lang. Leads to restart spaces manually anytime they want updates seems to me to be the greater of two evils compared to **sometimes breaking dash when left open for extended periods of time.

Agree that we need to identify underlying cause and resolve. Happy to investigate and resolve before we merge this.

**Comment by ignacioct** [comment]
> [here](https://discord.com/channels/879548962464493619/1205128865735770142/1221398680477630494)



> > Hi @kghamilton89, thanks for the PR. This code looks very similar to the code we initially had to allow background refresh, but it was giving us a lot of problems. The dashboard was getting frozen fairly regularly. Are you not experiencing this?
> > If it's working on your side, we could maybe add it as an option or comments in the code, but I and @dvsrepo are skeptics about the `BackgroundScheduler` usage.
> 
> In fact yes, sometimes I see that dashboard hangs when I leave it open for a period of time. Use case: I open dashboard and leave it open for an arbitrary period of time. I return to dash and see "error" for all visualizations. (confirmed that this occurs for our Dutch-speaking colleagues in same use case)
> 
> Refresh always resolves this issue and looking at console shows `500` error for Argilla servers.
> 
> Do you have any hypothesis for why this happens? As I say in [here](https://discord.com/channels/879548962464493619/1205128865735770142/1221398680477630494) expecting Lang. Leads to restart spaces manually anytime they want updates seems to me to be the greater of two evils compared to **sometimes breaking dash when left open for extended periods of time.
> 
> Maybe there is an issue with Argilla / HF Spaces integration? For example setting `share=True` in `launch()` returns that such a feature is not supported in HF Spaces. Maybe this indicates that other features are not supported also?
> 
> Agree that we need to identify underlying cause and resolve. Happy to investigate and resolve before we merge this.

Yep, you're getting the same error as we were getting. And we still have no clue why it is happening. Given the circumstances, we decided to manually update the dashboards from time to time, and we also looked into options for automatically resetting the space, which is possible. If you wanna go down the rabbit hole, it would be nice, but I personally believe it's worth it to look into how to automatically restart the spaces; I don't think having live, updated dashboards it's a priority, even though it'll be really nice.

**Comment by kghamilton89** [comment]
Fully understood @ignacioct, thanks for the feedback. I'll have a look and see what I can gather. In the meantime, closing PR.

**Pull request closed without merging**
